### ISSUE TITLE
PARAM_DICTIONARY_ACCENT_SENSITIVE for insensitive matching

### ISSUE THREAD

**Issue by jgrivolla** [tokenmill/dictionary-annotator#2]
According to `README.md` you have to set `DictionaryAnnotator.PARAM_DICTIONARY_ACCENT_SENSITIVE` to `true` in order to do accent _in_-sensitive matching. This seems to be either a documentation error or a bad choice of parameter name.

**Comment by dremeika** [comment]
Thanks for spotting this out. It was a documentation error. Fixed now.
